
version : '3.3'

services :
  scraper :
    build :
      context:  ./scraper
      dockerfile: Dockerfile
    volumes:
      - /home/rakesh/documents/data/logs:/logs
      - /home/rakesh/documents/data/database:/database
  
  streamlit:
    build :
      context:  ./streamlit
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    volumes:
      - /home/rakesh/documents/data/database:/database