
version : '3.9'

services :
  scraper :
    build :
      context:  ./scraper
      dockerfile: Dockerfile
    volumes:
      - /home/rakeshbhat9/dockertesting/logs:/logs
      - /home/rakeshbhat9/dockertesting/database:/database
  
  streamlit:
    build :
      context:  ./streamlit
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    volumes:
      - /home/rakeshbhat9/dockertesting/database:/database